-- MySQL Script generated by MySQL Workbench
-- Sun Feb 20 20:16:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema browser_game
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema browser_game
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `browser_game` DEFAULT CHARACTER SET utf8 ;
USE `browser_game` ;

-- -----------------------------------------------------
-- Table `browser_game`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `browser_game`.`usuarios` (
  `usuarioid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `senha` CHAR(32) NOT NULL,
  PRIMARY KEY (`usuarioid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `browser_game`.`personagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `browser_game`.`personagens` (
  `personagemid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuarioid` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `vida` INT NOT NULL,
  `vida_maxima` INT NOT NULL,
  `experiencia` INT NOT NULL,
  `experiencia_maxima` INT NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`personagemid`),
  INDEX `chave_estrangeira_1_idx` (`usuarioid` ASC) ,
  CONSTRAINT `chave_estrangeira_1`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `browser_game`.`usuarios` (`usuarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `browser_game`.`oponentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `browser_game`.`oponentes` (
  `oponenteid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `vida` INT NOT NULL,
  `vida_maxima` INT NOT NULL,
  `experiencia` INT NOT NULL,
  PRIMARY KEY (`oponenteid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
